username = input ("имя пользователя: ")
title = input ("заголовок заметки: ")
content = input ("описание заметки: ")
status = input("статус заметки: ")
created_date = input("дата создания заметки Д-М-Г: ")
issue_date = input("дата истечения заметки Д-М-Г: ")
print(username,)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)
